version: '3.7'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app
  db:
    image: mysql:8.0.29
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql-data:/var/lib/mysql
    networks:
      - app
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - app

networks:
  app:
    name: karaoke
    driver: bridge